restaurant/urls.py
from django.urls import path, include

from restaurant.views import (
    index,
    DishTypeListView,
    DishListView,
    CookListView,
    DishDetailView,
    CookDetailView,
    CookCreateView,
    CookExperienceUpdateView,
    DishCreateView,
    DishUpdateView,
    CookDeleteView,
    DishDeleteView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
)


urlpatterns = [
    path("", index, name="index"),
    path("dishtypes/", DishTypeListView.as_view(), name="dishtypes"),
    path("dishes/", DishListView.as_view(), name="dishes"),
    path("cooks/", CookListView.as_view(), name="cooks"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/update", CookExperienceUpdateView.as_view(), name="cook-update"),
    path("cooks/<int:pk>/delete", CookDeleteView.as_view(), name="cook-delete"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete", DishDeleteView.as_view(), name="dish-delete"),
    path("dishtypes/create/", DishTypeCreateView.as_view(), name="dishtype-create"),
    path("dishtypes/<int:pk>/update", DishTypeUpdateView.as_view(), name="dishtype-update"),
    path("dishtypes/<int:pk>/delete", DishTypeDeleteView.as_view(), name="dishtype-delete"),
]

app_name = "restaurant"

restaurant_kitchen_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("restaurant.urls", namespace="restaurant")),
    path("accounts/", include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

restaurant/models.py
from typing import List

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models


class DishType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Dish Types"

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE)
    cooks = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="dishes")

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Dishes"

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(blank=True, null=True)

    class Meta:
        ordering = ["username"]

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.username})"

restaurant/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from restaurant.models import Cook, Dish, DishType


class CookForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
            "password1",
            "password2",
            "first_name",
            "last_name",
            "years_of_experience"
        )


class UpdateExperienceForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = (
            "years_of_experience",
        )

    def clean_years_of_experience(self):
        years = self.cleaned_data["years_of_experience"]
        if years < 0 or years > 90:
            raise forms.ValidationError("Years of experience must be positive")
        return years


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=Cook.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Dish
        fields = (
            "__all__"
        )


class DishTypeForm(forms.ModelForm):
    class Meta:
        model = DishType
        fields = (
            "__all__"
        )

restaurant/views.py
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import generic

from restaurant.forms import CookForm, UpdateExperienceForm, DishForm, DishTypeForm
from restaurant.models import Dish, DishType, Cook

from django.urls import reverse_lazy


# Create your views here.

def index(request):
    num_dishes = Dish.objects.count()
    num_dish_types = DishType.objects.count()
    num_cooks = Cook.objects.count()

    context = {
        "num_dishes": num_dishes,
        "num_dish_types": num_dish_types,
        "num_cooks": num_cooks,
    }
    return render(request, "restaurant/index.html", context=context)


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 10


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = DishType


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookForm
    success_url = reverse_lazy("restaurant:cooks")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("restaurant:cooks")


class CookExperienceUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = UpdateExperienceForm
    success_url = reverse_lazy("restaurant:cooks")


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("restaurant:dishes")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("restaurant:dishes")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("restaurant:dishes")


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("restaurant:dishtypes")


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    form_class = DishTypeForm
    success_url = reverse_lazy("restaurant:dishtypes")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("restaurant:dishtypes")


# def my_view(request):
#     username = request.POST["username"]
#     password = request.POST["password"]
#     user = authenticate(request, username=username, password=password)
#     if user is not None:
#         login(request, user)
#         return  redirect
#         ...
#     else:
#         # Return an 'invalid login' error message.
#         ...

templates/base-fullscreen.html
<!--
=========================================================
* Soft UI Design System - v1.0.1
=========================================================

* Product Page: https://www.creative-tim.com/product/soft-ui-design-system
* Copyright 2021 Creative Tim (https://www.creative-tim.com)

Coded by www.creative-tim.com

 =========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="/static/assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="/static/assets/img/favicon.png">
  <link rel="canonical" href="#"/>
  
  <title>
    Django Soft UI Design System - {% block title %}{% endblock %} | AppSeed
  </title>

  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
  <!-- Nucleo Icons -->
  <link href="/static/assets/css/nucleo-icons.css" rel="stylesheet" />
  <link href="/static/assets/css/nucleo-svg.css" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <link href="/static/assets/css/nucleo-svg.css" rel="stylesheet" />
  <!-- CSS Files -->
  <link id="pagestyle" href="/static/assets/css/soft-design-system.css?v=1.0.1" rel="stylesheet" />

  <!-- Specific CSS goes HERE -->
  {% block stylesheets %}{% endblock stylesheets %}

</head>
<body class="{% block body_class %}{% endblock body_class %}">

    {% block content %}{% endblock content %}
  
    {% include "includes/scripts.html" %}

  <!-- Specific JS goes HERE --> 
  {% block javascripts %}{% endblock javascripts %}

</body>
</html>

templates/base-presentation.html
<!--
=========================================================
* Soft UI Design System - v1.0.1
=========================================================

* Product Page: https://www.creative-tim.com/product/soft-ui-design-system
* Copyright 2021 Creative Tim (https://www.creative-tim.com)

Coded by www.creative-tim.com

 =========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="/static/assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="/static/assets/img/favicon.png">
  <link rel="canonical" href="#"/>
  
  <title>
    Kitchen Service {% block title %}{% endblock %}
  </title>

  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
  <!-- Nucleo Icons -->
  <link href="/static/assets/css/nucleo-icons.css" rel="stylesheet" />
  <link href="/static/assets/css/nucleo-svg.css" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

  <link href="/static/assets/css/nucleo-svg.css" rel="stylesheet" />
  <!-- CSS Files -->
  <link id="pagestyle" href="/static/assets/css/soft-design-system.css?v=1.0.1" rel="stylesheet" />

  <!-- Specific CSS goes HERE -->
  {% block stylesheets %}{% endblock stylesheets %}

</head>

<body class="{% block body_class %}{% endblock body_class %}">

    {% include "includes/navigation.html" %}

    {% block content %}{% endblock content %}
  
    {% include "includes/footer.html" %}

    {% include "includes/scripts.html" %}

  <!-- Specific JS goes HERE --> 
  {% block javascripts %}{% endblock javascripts %}

</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  {% block title %}
    <title>Main page</title>
  {% endblock %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href={% static "css/styles.css" %}>
</head>
<body>
<div class="container-fluid">
  <div class="row">

    <div class="col-sm-3">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    </div>

    <div class="col-sm-9">
        {% block content %}{% endblock %}
      {% block pagination %}
        {% include "includes/paginator.html" %}
    {% endblock %}
    </div>

  </div>
</div>
</body>
</html>

templates/includes/footer.html
  <footer class="footer pt-5 mt-5">
    <hr class="horizontal dark mb-5">
    <div class="container">
      <div class=" row">
        <div class="col-md-3 mb-4 ms-auto">
          <div>
            <h6 class="text-gradient text-primary font-weight-bolder">Soft UI Design System</h6>
          </div>
          <div>
            <h6 class="mt-3 mb-2 opacity-8">Social</h6>
            <ul class="d-flex flex-row ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link pe-1" href="#" target="_blank">
                  <i class="fab fa-facebook text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="#" target="_blank">
                  <i class="fab fa-twitter text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="#" target="_blank">
                  <i class="fab fa-dribbble text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="#" target="_blank">
                  <i class="fab fa-github text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="#" target="_blank">
                  <i class="fab fa-youtube text-lg opacity-8"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-gradient text-primary text-sm">Company</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  About Us
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Freebies
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Premium Tools
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Blog
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-gradient text-primary text-sm">Help & Support</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Contact Us
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Knowledge Center
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Custom Development
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Sponsorships
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4 me-auto">
          <div>
            <h6 class="text-gradient text-primary text-sm">Legal</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Terms & Conditions
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Privacy Policy
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Licenses (EULA)
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-12">
          <div class="text-center">
            <p class="my-4 text-sm">
              Kitchen Management &copy; <a target="_blank" href="https://bit.ly/3fKQZaL" target="_blank"></a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/includes/navigation-auth.html
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid">
            <a class="navbar-brand font-weight-bolder ms-sm-3" 
               href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              Kitchen Management System
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2" href="https://github.com/Dimdimior" target="_blank">
                    <i class="fa fa-github me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Star us on Github">Github</p>
                  </a>
                </li>
                <li class="nav-item my-auto ms-3 ms-lg-0">
                  <a href="#"
                     class="btn btn-sm  bg-gradient-primary  btn-round mb-0 me-1 mt-2 mt-md-0">Our products</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/navigation.html
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid">
            <a class="navbar-brand font-weight-bolder ms-sm-3" 
               href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              Kitchen Management System
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
              <ul class="navbar-nav navbar-nav-hover  ps-lg-5 w-100">
                <h6 style="margin-top: 5px; padding-left: 20%" ><a href={% url "restaurant:cooks" %}>Cooks</a></h6>
                <h6 style="margin-top: 5px ; padding-left: 20px"><a href={% url "restaurant:dishes" %}>Dishes</a></h6>
                <h6 style="margin-top: 5px ; padding-left: 20px"><a href={% url "restaurant:dishtypes" %}>Types</a></h6>
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2" href="https://github.com/Dimdimior" target="_blank">
                    <i class="fa fa-github me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="My profile on Github">Github</p>
                  </a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item my-auto ms-3 ms-lg-0">
                  <a href={% url "logout" %}
                         class="btn btn-sm  bg-gradient-primary  btn-round mb-0 me-1 mt-2 mt-md-0">Logout as {{ user.username }}<a></a>
                </li>
                  {% else %}
                  <li class="nav-item my-auto ms-3 ms-lg-0">
                  <a href={% url "login" %}?next={% url "restaurant:index" %}
                     class="btn btn-sm  bg-gradient-primary  btn-round mb-0 me-1 mt-2 mt-md-0">Login</a>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/paginator.html
{% if is_paginated %}
    <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
      <a href="?page={{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
      {% endif %}

    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>

    {% if page_obj.has_next %}
      <li class="page-item">
      <a href="?page={{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
      {% endif %}
    </ul>
  {% endif %}

templates/includes/scripts.html
  <script src="/static/assets/js/core/popper.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="/static/assets/js/plugins/prism.min.js"></script>
  <script src="/static/assets/js/plugins/parallax.min.js"></script>

templates/includes/sidebar.html
<ul class="sidebar-nav">
    {% if user.is_authenticated %}
    <li class="list-group-item">User: <a href="{% url "restaurant:cook-detail" pk=user.id %}">{{ user.get_username }}</a></li>
    <li class="list-group-item"><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
  {% endif %}

  <br>

    <li><a href="{% url "restaurant:index" %}">Home</a></li>
    <li><a href={% url "restaurant:dishtypes" %}>All dish types</a></li>
    <li><a href={% url "restaurant:dishes" %}>All dishes</a></li>
    <li><a href={% url "restaurant:cooks" %}>All cooks</a></li>
</ul>

templates/restaurant/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete cook?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/restaurant/cook_detail.html
{% extends "base.html" %}

{% block content %}
  <h2>{{ cook.first_name }} {{ cook.last_name }}
  <a href="{% url "restaurant:cook-update" pk=cook.id %}" class="btn btn-primary link-to-page">Update experience</a>

    <a href="{% url "restaurant:cook-delete" pk=cook.id %}" class="btn btn-primary link-to-page">Delete cook</a>
</h2>
  {% if cook.years_of_experience == 1 %}
    <p><strong>Experience:</strong> {{ cook.years_of_experience }} year</p>
  {% else %}
    <p><strong>Experience:</strong> {{ cook.years_of_experience }} years</p>
  {% endif %}
  <p><strong>Favourite dishes:</strong></p>
  {% if cook.dishes.all %}
    {% for dish in cook.dishes.all %}
      <ul>
        <li><a href={% url "restaurant:dish-detail" pk=dish.id %}>{{ dish.name }}</a></li>
      </ul>
    {% endfor %}
  {% else %}
    <p>This cook has no favourite dishes yet</p>
  {% endif %}

{% endblock %}

templates/restaurant/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create cook</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/restaurant/cook_list.html
{#{% extends "base-presentation.html" %}#}

{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div class="col-12">
      <h1>Cook List
        <a href="{% url "restaurant:cook-create" %}" class="btn btn-primary link-to-page">
      Create
        </a>
      </h1>
    </div>
  </div>
<div class="row">
  <div class="col-5">
      {% if cook_list %}
  <ul>
    {% for cook in cook_list %}
      <li><a href={% url "restaurant:cook-detail" pk=cook.id %}>{{ cook.first_name}} {{ cook.last_name }} ({{ cook.username }})</a></li>
    {% endfor %}
  </ul>
  {% else %}
      <p>There are no cooks</p>
{% endif %}
  </div>
</div>
{% endblock %}

templates/restaurant/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete dish?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/restaurant/dish_detail.html
{% extends "base.html" %}

{% block content %}
  <h2>{{ dish.name }}
  <a href="{% url "restaurant:dish-update" pk=dish.id %}" class="btn btn-danger link-to-page">
      Update
    </a>

    <a href="{% url 'restaurant:dish-delete' pk=dish.id %}" class="btn btn-secondary link-to-page">
      Delete
    </a>
  </h2>

  <section>{{ dish.description }}</section>
  <br>
  <p><strong>Cooks:</strong></p>
  {% for cook in dish.cooks.all %}
    <ul>
      <li><a href={% url "restaurant:cook-detail" pk=cook.id %}>{{ cook.first_name }} {{ cook.last_name }}</a></li>
    </ul>
  {% endfor %}

{% endblock %}

templates/restaurant/dish_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Dish list
    <a href="{% url "restaurant:dish-create" %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
  {% if dish_list %}
    <ul>
      {% for dish in dish_list %}
        <li><a href={% url "restaurant:dish-detail" pk=dish.id %} >{{ dish.name }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no dishes</p>
  {% endif %}

{% endblock %}

templates/restaurant/dishtype_list.html
{% extends "base.html" %}

{% block content %}
<h1>DishType List
  <a href="{% url "restaurant:dishtype-create" %}" class="btn btn-primary link-to-page">
      Create
    </a>
</h1>
{% if dishtype_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for dishtype in dishtype_list %}
        <tr>
          <td>
              {{ dishtype.id }}
          </td>
          <td>
              {{ dishtype.name }}
          </td>
          <td>
              <a href="{% url 'restaurant:dishtype-update' pk=dishtype.id %}">
                Update
              </a>
            </td>
            <td>
              <a style="color: red"
                href="{% url 'restaurant:dishtype-delete' pk=dishtype.id %}">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no dishtypes in the base.</p>
  {% endif %}
{% endblock %}